---
# handlers file for panxatony.logstash

- name: restart logstash
  service: name=logstash state=restarted
  become: yes
  become_user: root

- name: restart nginx
  service: name=nginx state=restarted
  become: yes
  become_user: root